# SPDX-FileCopyrightText: Copyright Preetham Gujjula
# SPDX-License-Identifier: BSD-3-Clause
spec-version: 0.36.0
name:         vcard
version:      0.0.0.0
# synopsis:   Short description of your package
description:  Please see the README on GitHub at <https://github.com/pgujjula/vcard#readme>
# category:   Web
stability:    experimental
github:       "pgujjula/vcard"
author:       "Preetham Gujjula"
maintainer:   "libraries@mail.preetham.io"
copyright:    "Preetham Gujjula"
license:      BSD-3-Clause

tested-with:
- GHC == 9.4.8
- GHC == 9.6.6

extra-doc-files:
- README.md
- CHANGELOG.md
- LICENSES/BSD-3-Clause.txt

language: Haskell2010

default-extensions:
- ImportQualifiedPost

dependencies:
- base ^>= {4.17, 4.18}

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages

library:
  source-dirs: src
  exposed-modules:
  - VCard
  - VCard.Types.Param
  - VCard.Types.Property
  - VCard.Types.Value
  - VCard.Types.VCard
  other-modules:
  - VCard.Parse
  - VCard.Serialize
  - VCard.Types.Property.Version
  - VCard.Types.Value.Date
  - VCard.Types.Value.List
  - VCard.Types.Value.Text
  - VCard.Types.Value.URI
  - VCard.Types.VCard.Internal
  - VCard.Util
  dependencies:
  - containers ^>= {0.6, 0.7}
  - finite-typelits ^>= {0.1, 0.2}
  - megaparsec >= 9.0 && < 10
  - network-uri ^>= {2.6}
  - text ^>= {1.2, 2.0, 2.1}
  - text-show ^>= {3.10, 3.11}

tests:
  vcard-tests:
    main: Main.hs
    source-dirs:
    # To allow importing library internals in the test-suite, we add the add the
    # library source files in 'src' directly to the test-suite, instead of
    # adding the library as a dependency. This means that the files in 'src' are
    # compiled twice, once as part of the library and once as part of the test
    # suite.
    - src
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers ^>= {0.6, 0.7}
    - data-ordlist ^>= {0.4}
    - finite-typelits ^>= {0.1, 0.2}
    - genvalidity-network-uri ^>= {0.0}
    - megaparsec >= 9.0 && < 10
    - network-uri ^>= {2.6}
    - tasty ^>= {1.4, 1.5}
    - tasty-hunit ^>= {0.10}
    - tasty-quickcheck ^>= {0.10, 0.11}
    - text ^>= {1.2, 2.0, 2.1}
    - text-show ^>= {3.10, 3.11}
    - time ^>= {1.12, 1.14}
