# SPDX-FileCopyrightText: Copyright Preetham Gujjula
# SPDX-License-Identifier: BSD-3-Clause
spec-version: 0.36.0
name:         vcard
version:      0.0.0.0
# synopsis:   Short description of your package
description:  Please see the README on GitHub at <https://github.com/pgujjula/vcard#readme>
# category:   Web
stability:    experimental
github:       "pgujjula/vcard"
author:       "Preetham Gujjula"
maintainer:   "libraries@mail.preetham.io"
copyright:    "Preetham Gujjula"
license:      BSD-3-Clause

tested-with:
- GHC == 9.2.8
- GHC == 9.4.8
- GHC == 9.6.6
- GHC == 9.8.4
- GHC == 9.10.1
- GHC == 9.12.1

extra-doc-files:
- CHANGELOG.md
- LICENSES/BSD-3-Clause.txt
- README.md

language: Haskell2010

default-extensions:
- ConstraintKinds
- DataKinds
- FlexibleContexts
- FlexibleInstances
- GADTs
- ImportQualifiedPost
- InstanceSigs
- KindSignatures
- LambdaCase
- NoStarIsType
- PolyKinds
- RankNTypes
- StandaloneDeriving
- ScopedTypeVariables
- TypeApplications
- TypeOperators

dependencies:
- base ^>= {4.16, 4.17, 4.18, 4.19, 4.20, 4.21}

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages
when:
- condition: impl(ghc < 9.4)
  ghc-options:
  - -Wno-unticked-promoted-constructors

library:
  source-dirs: src
  exposed-modules:
  - VCard
  - VCard.Types.Param
  - VCard.Types.Property
  - VCard.Types.VCard
  - VCard.Types.Value
  other-modules:
  - VCard.AlphaNumDash
  - VCard.CaseInsensitive
  - VCard.Char
  - VCard.Internal.Closed
  - VCard.Natural.Private
  - VCard.Natural.Private.Compat
  - VCard.Parse
  - VCard.Serialize
  - VCard.Symbol.Private
  - VCard.Symbol.Private.Append
  - VCard.Symbol.Private.Case
  - VCard.Symbol.Private.Compat
  - VCard.Symbol.Private.Length
  - VCard.Symbol.Private.List
  - VCard.Symbol.Private.Prefix
  - VCard.Symbol.Private.Singleton
  - VCard.Symbol.Private.Slice
  - VCard.Types.Param.Calscale
  - VCard.Types.Param.Calscale.CalscaleValueSymbol
  - VCard.Types.Param.Generic
  - VCard.Types.Param.Geo
  - VCard.Types.Param.Language
  - VCard.Types.Param.PID
  - VCard.Types.Param.Pref
  - VCard.Types.Param.Type
  - VCard.Types.Param.Type.TypeValueSymbol
  - VCard.Types.Param.Value
  - VCard.Types.Param.Value.ValueValueSymbol
  - VCard.Types.Property.Version
  - VCard.Types.VCard.Internal
  - VCard.Types.Value.Boolean
  - VCard.Types.Value.Date
  - VCard.Types.Value.Float
  - VCard.Types.Value.Integer
  - VCard.Types.Value.LanguageTag
  - VCard.Types.Value.List
  - VCard.Types.Value.Text
  - VCard.Types.Value.Time
  - VCard.Types.Value.URI
  - VCard.Util
  - VCard.XName
  dependencies:
  - constraints ^>= {0.13, 0.14}
  - containers ^>= {0.6, 0.7, 0.8}
  - finite-typelits ^>= {0.1, 0.2}
  - megaparsec >= 9.0 && < 10
  - network-uri ^>= {2.6}
  - parser-combinators ^>= {1.3}
  - scientific ^>= {0.3}
  - singletons-base ^>= {3.0, 3.1, 3.2, 3.3, 3.4, 3.5}
  - text ^>= {1.2, 2.0, 2.1}
  - vary ^>= {0.1}
  when:
  - condition: impl(ghc >= 9.6)
    other-modules:
    - VCard.Natural.Private.Compat.New
    - VCard.Symbol.Private.Compat.New
  - condition: impl(ghc < 9.6)
    other-modules:
    - VCard.Natural.Private.Compat.Old
    - VCard.Symbol.Private.Compat.Old

tests:
  vcard-tests:
    main: Main.hs
    source-dirs:
    # To allow importing library internals in the test-suite, we add the add the
    # library source files in 'src' directly to the test-suite, instead of
    # adding the library as a dependency. This means that the files in 'src' are
    # compiled twice, once as part of the library and once as part of the test
    # suite.
    - src
    - test
    other-modules:
    - Test.VCard
    - Test.VCard.AlphaNumDash
    - Test.VCard.AlphaNumDash.TypeTests
    - Test.VCard.CaseInsensitive
    - Test.VCard.Char
    - Test.VCard.Natural.Private
    - Test.VCard.Natural.Private.Compat
    - Test.VCard.Symbol.Private
    - Test.VCard.Symbol.Private.Case
    - Test.VCard.Symbol.Private.Compat
    - Test.VCard.Symbol.Private.Length
    - Test.VCard.Symbol.Private.List
    - Test.VCard.Symbol.Private.Prefix
    - Test.VCard.Symbol.Private.Singleton
    - Test.VCard.Symbol.Private.Slice
    - Test.VCard.Types
    - Test.VCard.Types.Param
    - Test.VCard.Types.Param.Calscale
    - Test.VCard.Types.Param.Generic
    - Test.VCard.Types.Param.Geo
    - Test.VCard.Types.Param.Language
    - Test.VCard.Types.Param.PID
    - Test.VCard.Types.Param.Pref
    - Test.VCard.Types.Param.Value
    - Test.VCard.Types.Param.Type
    - Test.VCard.Types.Property
    - Test.VCard.Types.Property.Version
    - Test.VCard.Types.VCard
    - Test.VCard.Types.Value
    - Test.VCard.Types.Value.Boolean
    - Test.VCard.Types.Value.Date
    - Test.VCard.Types.Value.Float
    - Test.VCard.Types.Value.Integer
    - Test.VCard.Types.Value.LanguageTag
    - Test.VCard.Types.Value.Text
    - Test.VCard.Types.Value.Time
    - Test.VCard.Types.Value.URI
    - Test.VCard.Util
    - Test.VCard.XName
    - Test.VCard.XName.TypeTests
    - VCard
    - VCard.AlphaNumDash
    - VCard.CaseInsensitive
    - VCard.Char
    - VCard.Internal.Closed
    - VCard.Natural.Private
    - VCard.Natural.Private.Compat
    - VCard.Parse
    - VCard.Serialize
    - VCard.Symbol.Private
    - VCard.Symbol.Private.Append
    - VCard.Symbol.Private.Case
    - VCard.Symbol.Private.Compat
    - VCard.Symbol.Private.Length
    - VCard.Symbol.Private.List
    - VCard.Symbol.Private.Prefix
    - VCard.Symbol.Private.Singleton
    - VCard.Symbol.Private.Slice
    - VCard.Types.Param
    - VCard.Types.Param.Calscale
    - VCard.Types.Param.Calscale.CalscaleValueSymbol
    - VCard.Types.Param.Generic
    - VCard.Types.Param.Geo
    - VCard.Types.Param.Language
    - VCard.Types.Param.PID
    - VCard.Types.Param.Pref
    - VCard.Types.Param.Type
    - VCard.Types.Param.Type.TypeValueSymbol
    - VCard.Types.Param.Value
    - VCard.Types.Param.Value.ValueValueSymbol
    - VCard.Types.Property
    - VCard.Types.Property.Version
    - VCard.Types.VCard
    - VCard.Types.VCard.Internal
    - VCard.Types.Value
    - VCard.Types.Value.Boolean
    - VCard.Types.Value.Date
    - VCard.Types.Value.Float
    - VCard.Types.Value.Integer
    - VCard.Types.Value.LanguageTag
    - VCard.Types.Value.List
    - VCard.Types.Value.Text
    - VCard.Types.Value.Time
    - VCard.Types.Value.URI
    - VCard.Util
    - VCard.XName
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - constraints ^>= {0.13, 0.14}
    - containers ^>= {0.6, 0.7, 0.8}
    - data-ordlist ^>= {0.4}
    - deepseq ^>= {1.4, 1.5, 1.6}
    - finite-typelits ^>= {0.1, 0.2}
    - genvalidity-network-uri ^>= {0.0}
    - megaparsec >= 9.0 && < 10
    - network-uri ^>= {2.6}
    - parser-combinators ^>= {1.3}
    - scientific ^>= {0.3}
    - should-not-typecheck ^>= {2.1}
    - singletons-base ^>= {3.0, 3.1, 3.2, 3.3, 3.4, 3.5}
    - tasty ^>= {1.4, 1.5}
    - tasty-hunit ^>= {0.10}
    - tasty-quickcheck ^>= {0.10, 0.11}
    - text ^>= {1.2, 2.0, 2.1}
    - time ^>= {1.11, 1.12, 1.14}
    - vary ^>= {0.1}
    when:
    - condition: impl(ghc >= 9.6)
      other-modules:
      - VCard.Natural.Private.Compat.New
      - VCard.Symbol.Private.Compat.New
    - condition: impl(ghc < 9.6)
      other-modules:
      - VCard.Natural.Private.Compat.Old
      - VCard.Symbol.Private.Compat.Old
