# SPDX-FileCopyrightText: Copyright Preetham Gujjula
# SPDX-License-Identifier: BSD-3-Clause
resolver: lts-21.25
packages:
- .

extra-deps:
- ghc-tcplugin-api-0.11.0.0
- genvalidity-network-uri-0.0.0.0
- large-generics-0.2.2
- typelet-0.1.4
- validity-network-uri-0.0.0.0
- vary-0.1.1.0
- large-anon-0.3.1

flags:
  vary:
    aeson: false
    binary: false
    cereal: false
    hashable: false
    quickcheck: false
  large-anon:
    disablefourmoluexec: true
