# SPDX-FileCopyrightText: Copyright Preetham Gujjula
# SPDX-License-Identifier: BSD-3-Clause
resolver: lts-22.43
compiler: ghc-9.6.7

packages:
- .

extra-deps:
- vary-0.1.1.0

flags:
  vary:
    aeson: false
    binary: false
    cereal: false
    hashable: false
    quickcheck: false
