# SPDX-FileCopyrightText: Copyright Preetham Gujjula
# SPDX-License-Identifier: BSD-3-Clause
resolver: lts-21.25
packages:
- .

extra-deps:
- genvalidity-network-uri-0.0.0.0
- validity-network-uri-0.0.0.0
- vary-0.1.0.3
