# SPDX-FileCopyrightText: Copyright Preetham Gujjula
# SPDX-License-Identifier: BSD-3-Clause
when:
  - branch: main
    event: [pull_request, pull_request_closed, push]
  - event: manual

depends_on:
  - reuse
  - ormolu

matrix:
  GHC_VERSION:
    - 9.2.8
    - 9.4.8
    - 9.6.7
    - 9.8.4
    - 9.10.3
    - 9.12.2

steps:
  - name: build_test_${GHC_VERSION}
    image: haskell:${GHC_VERSION}
    commands:
      - cabal update
      - cabal configure
          --enable-tests
          --test-show-details=streaming
          --enable-benchmarks
          --ghc-options="-Werror"
          --test-options='-p "$0 !~ /exhaustive/"'
          --disable-optimization
      - cabal outdated --exit-code --ignore=base
      - cabal build -j4
      - cabal test
