# SPDX-FileCopyrightText: Copyright Preetham Gujjula
# SPDX-License-Identifier: BSD-3-Clause
when:
    branch: main
    event: [manual, pull_request]

depends_on:
  - reuse
  - ormolu

matrix:
  include:
    - GHC_VERSION: 9.2.8
      SOURCE: haskell
    - GHC_VERSION: 9.4.8
      SOURCE: haskell
    - GHC_VERSION: 9.6.6
      SOURCE: haskell
    - GHC_VERSION: 9.8.4
      SOURCE: haskell
    - GHC_VERSION: 9.10.1-slim-bullseye
      SOURCE: haskell
    - GHC_VERSION: 9.12.1
      SOURCE: benz0li/ghc-musl

steps:
  - name: build_test_${GHC_VERSION}
    image: ${SOURCE}:${GHC_VERSION}
    commands:
      - cabal update
      - cabal configure
          --enable-tests
          --test-show-details=streaming
          --enable-benchmarks
          --ghc-options="-Werror"
          --test-options='-p "$0 !~ /exhaustive/"'
          --disable-optimization
      - cabal outdated --exit-code --ignore=base
      - cabal build -j1
      - cabal test
