# SPDX-FileCopyrightText: Copyright Preetham Gujjula
# SPDX-License-Identifier: BSD-3-Clause
when:
  - branch: main
    event: [pull_request_closed, push]
  - event: manual

depends_on:
  - build_test

steps:
  - name: publish_docs
    image: haskell:9.6.7
    environment:
      VCARD_PUBLISH_DOCS_PRIVATE_KEY:
        from_secret: vcard_publish_docs_private_key
      VCARD_PUBLISH_DOCS_PUBLIC_KEY:
        from_secret: vcard_publish_docs_public_key
    commands:
      # Need bullseye-backports for git >= 2.34
      - echo "deb https://archive.debian.org/debian bullseye-backports main" >/etc/apt/sources.list.d/bullseye-backports.list
      - apt-get update

      # Setup ssh
      - apt-get install -y openssh-client
      - eval $(ssh-agent -s)
      - echo "$${VCARD_PUBLISH_DOCS_PRIVATE_KEY}" | ssh-add -
      - ssh-add -l
      - mkdir ~/.ssh
      - ssh-keyscan -H codeberg.org >> ~/.ssh/known_hosts

      # Set up git
      - apt-get install -y git/bullseye-backports
      - git config --global user.email "gitcommit@mail.preetham.io"
      - git config --global user.name "Preetham Gujjula"
      - git config --global user.signingkey "$${VCARD_PUBLISH_DOCS_PUBLIC_KEY}"
      - git config --global gpg.format "ssh"
      - git config --global commit.gpgsign "true"

      # Build docs
      - stack build --fast --haddock

       # Push docs
      - cd ~
      - git clone ssh://git@codeberg.org/pgujjula/vcard-docs.git
      - cd -
      - cp -r $(stack path --local-doc-root)/* ~/vcard-docs/
      - cd ~/vcard-docs/
      - git add .
      - git commit --amend --no-edit -S
      - git push origin --force-with-lease
