# SPDX-FileCopyrightText: Copyright Preetham Gujjula
# SPDX-License-Identifier: BSD-3-Clause
when:
    branch: main
    event: [push, pull_request]

steps:
  - name: reuse
    image: fsfe/reuse
    commands: reuse lint
